### ISSUE TITLE
 installation of package ‘RcppGSL’ had non-zero exit status

### ISSUE THREAD

**Issue by sariya** [eddelbuettel/rcppgsl#26] opened 2020-08-26 15:38 UTC
Sorry for opening this small installation error.
 `install.packages("RcppGSL")` give me error and fails:

Similarly I get error for rcppziggurat installation https://github.com/eddelbuettel/rcppziggurat/issues/12
I'm sharing warnings and messages generated during installation of `RppGSL`
```
Installing package into ‘/mnt/mfs/more/path/libraries_R/R_LIB4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.uib.no/src/contrib/RcppGSL_0.3.8.tar.gz'
Content type 'application/x-gzip' length 465170 bytes (454 KB)
==================================================
downloaded 454 KB

* installing *source* package ‘RcppGSL’ ...
** package ‘RcppGSL’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... /usr/bin/gsl-config
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/mnt/mfs/path/bin/R-4.0.0/include" -DNDEBUG -I/usr/include -I../inst/include -I'/mnt/mfs/path/bin/R-4.0.0/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/mnt/mfs/path/bin/R-4.0.0/include" -DNDEBUG -I/usr/include -I../inst/include -I'/mnt/mfs/path/bin/R-4.0.0/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c fastLm.cpp -o fastLm.o
gcc -I"/mnt/mfs/path/bin/R-4.0.0/include" -DNDEBUG -I/usr/include -I../inst/include -I'/mnt/mfs/path/bin/R-4.0.0/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
g++ -std=gnu++11 -I"/mnt/mfs/path/bin/R-4.0.0/include" -DNDEBUG -I/usr/include -I../inst/include -I'/mnt/mfs/path/bin/R-4.0.0/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c setErrorHandler.cpp -o setErrorHandler.o
g++ -std=gnu++11 -shared -L/mnt/mfs/path/bin/R-4.0.0/lib -L/usr/local/lib -o RcppGSL.so RcppExports.o fastLm.o init.o setErrorHandler.o -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -L/mnt/mfs/cluster/bin/R-4.0.0/lib -lR
/usr/bin/ld: /usr/local/lib/libgslcblas.a(xerbla.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/mnt/mfs/path/bin/R-4.0.0/share/make/shlib.mk:6: recipe for target 'RcppGSL.so' failed
make: *** [RcppGSL.so] Error 1
ERROR: compilation failed for package ‘RcppGSL’
* removing ‘/mnt/mfs/more/path/libraries_R/R_LIB4.0/RcppGSL’

The downloaded source packages are in
        ‘/tmp/Rtmpu3IFPc/downloaded_packages’
Warning message:
In install.packages("RcppGSL") :
  installation of package ‘RcppGSL’ had non-zero exit status

```

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

```

```
 .libPaths()
[1] "/mnt/mfs/hgrcgrid/more/path/libraries_R/R_LIB4.0"
[2] "/mnt/mfs/path/R-4.0.0/library"

```

**Comment by eddelbuettel** [comment] 2020-08-26 16:44
Please try `sudo apt-get install r-cran-rcppgsl` as you are on Debian which has a binary package.

Otherwise, the error 

```sh
/usr/bin/ld: /usr/local/lib/libgslcblas.a(xerbla.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' 
  can not be used when making a shared object; recompile with -fPIC
```
means that you system is not set up correctly for shared libraries.  Maybe you compiled R yourself -- if so it looks like you used the wrong options.

There are premade (and correctly configure) binaries for R on Debian at CRAN,  see http://cloud.r-project.org/bin/linux/debian/

Otherwise I am going to close this as there isn't actually a reproducible error in RcppGSL here -- unless I am reading this wrong (and then please correct me with additional information) this is likely a local setup issue.

**Closed by eddelbuettel** 2020-08-26 16:44 UTC

**Comment by sariya** [comment] 2020-08-26 19:11
Thank you, it was settings issue. . For anyone in the future if error is experienced:

In `~/.R/Makevars` add the following lines:
```

CXXPICFLAGS= -fPIC
LDFLAGS= /mnt/mfs/cluster/bin/GSL1.15/lib/libgslcblas.a 

```
If `.R` isn't present create .R directory at home then create Makevars file within it. :)

**Comment by eddelbuettel** [comment] 2020-08-26 19:33
If I may, that is somewhat bad / surely non-standard advice and applicable only to _your_ cluster mounted and that built that way.

Other users of RcppGSL should install as they always do, and/or rely on the pre-made binaries where available.

**Comment by Leitemfa** [comment] 2021-11-15 15:22
Hi,

Sorry for bringing this issue back to life, but I have a similar problem that I can not solve with `sudo` install since I do not have admin priviliges.

```
install.packages("RcppGSL")
Installing package into ‘/home/nioo/marciol/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/RcppGSL_0.3.10.tar.gz'
Content type 'application/x-gzip' length 469346 bytes (458 KB)
==================================================
downloaded 458 KB

* installing *source* package ‘RcppGSL’ ...
** package ‘RcppGSL’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘RcppGSL’
* removing ‘/home/nioo/marciol/R/x86_64-pc-linux-gnu-library/4.0/RcppGSL’
* restoring previous ‘/home/nioo/marciol/R/x86_64-pc-linux-gnu-library/4.0/RcppGSL’
Warning in install.packages :
  installation of package ‘RcppGSL’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpgKvG95/downloaded_packages’
```
I can install GSL within a conda environment (`/home/nioo/marciol/.conda/pkgs/gsl-2.7-he838d99_0/`), but how can I tell the `install.packages` function that there is a path to find the GSL config file?

**Comment by eddelbuettel** [comment] 2021-11-15 15:58
Please do not hijack old threads.  If you have something material, construct a minimally complete and verifiable example and open a new issue -- if you checked that your question is in fact new.

**Comment by Leitemfa** [comment] 2021-11-15 16:34
ok, sorry, I will open a new issue
