### ISSUE TITLE
RcppGSL>=0.3.5 fails to build on macOS

### ISSUE THREAD

**Issue by nieder** [eddelbuettel/rcppgsl#19] opened 2019-03-25 10:37 UTC
On macOS, trying to build versions 0.3.5 and 0.3.6 fail with this error (tried R-3.3 to R-3.5):
````
R --verbose CMD build --no-build-vignettes RcppGSL
* checking for file 'RcppGSL/DESCRIPTION' ... OK
* preparing 'RcppGSL':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running 'cleanup'
* installing the package to process help pages
      -----------------------------------
* installing *source* package 'RcppGSL' ...
file 'build/partial.rdb' is missing
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/RtmphalCcC/Rbuildc12283c934a/RcppGSL':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package 'RcppGSL'
* removing '/private/tmp/RtmphalCcC/Rinstc1220e9f3e9/RcppGSL'
      -----------------------------------
ERROR: package installation failed
````
Unfortunately, there's no config.log left to try and debug.

0.3.4 builds fine.

**Comment by eddelbuettel** [comment] 2019-03-25 10:39
That is not what CRAN shows [in its results page](https://cloud.r-project.org/web/checks/check_results_RcppGSL.html) which has 'OK' everywhere, including macOS.

Can you try the r-sig-mac list, please?  This looks like a _setup error on your end_ as configure fails with `checking whether the C compiler works... no` which is not RcppGSL's fault:  we need a working compiler as a precondition.

I suggest we close this in light of the builds at CRAN.

**Comment by nieder** [comment] 2019-03-25 10:44
I'll try there. But this is the first Rmod I've had that fails like this. I've compiled dozens other Rmods w/ no problems using the same build process on the same machine. And RcppGSL-0.3.4 compiles fine.

**Comment by eddelbuettel** [comment] 2019-03-25 10:57
If you check the [ChangeLog](https://github.com/eddelbuettel/rcppgsl/blob/master/ChangeLog) we altered nothing with respect to the build system.  So I don't see what would make 0.3.4 different in that regard.

**Comment by nieder** [comment] 2019-03-25 11:01
I saw that when I diffed the tarballs. The only other difference is in the binary build/partial.rdb, which is absent in 0.3.4

**Comment by eddelbuettel** [comment] 2019-03-25 11:06
Unpack 0.3.6. Run `./configure` by hand.  Check the log it produces.

**Comment by nieder** [comment] 2019-03-25 11:20
./configure inside the tarball works.
````
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... /sw/bin/gsl-config
configure: creating ./config.status
````

**Comment by eddelbuettel** [comment] 2019-03-25 11:37
Then its your R setup passing the wrong compiler info on. Check r-sig-mac.  I cannot help you as I cannot reproduce.  I will close this now -- I hope you don't mind.   If and when we have an issue in the package that manifests itself on more machines (ie if someone from r-sig-mac confirms) please reopen with pertinent info.  Patches would be even better -- I don't have a macOS machine.

**Closed by eddelbuettel** 2019-03-25 11:37 UTC

**Comment by eddelbuettel** [comment] 2019-03-25 11:41
PS In case you get nothing helpful from r-sig-mac (though I think you will) you can also try the rcpp-devel as several people there use macOS machines.

**Comment by kevinushey** [comment] 2019-03-26 00:20
Everything's fine on my machine:

```R
> install.packages("RcppGSL", type = "source")
Installing package into ‘/Users/kevin/Library/R/3.5/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/RcppGSL_0.3.6.tar.gz'
Content type 'application/x-gzip' length 434843 bytes (424 KB)
==================================================
downloaded 424 KB

* installing *source* package ‘RcppGSL’ ...
** package ‘RcppGSL’ successfully unpacked and MD5 sums checked
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... /usr/local/bin/gsl-config
configure: creating ./config.status
config.status: creating src/Makevars
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/gsl/2.5/include -I../inst/include -I"/Users/kevin/Library/R/3.5/library/Rcpp/include" -I/usr/local/include   -fPIC  -g -O2 -Wall -c RcppExports.cpp -o RcppExports.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/gsl/2.5/include -I../inst/include -I"/Users/kevin/Library/R/3.5/library/Rcpp/include" -I/usr/local/include   -fPIC  -g -O2 -Wall -c fastLm.cpp -o fastLm.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/gsl/2.5/include -I../inst/include -I"/Users/kevin/Library/R/3.5/library/Rcpp/include" -I/usr/local/include   -fPIC  -g -O3 -Wall -pedantic -c init.c -o init.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/gsl/2.5/include -I../inst/include -I"/Users/kevin/Library/R/3.5/library/Rcpp/include" -I/usr/local/include   -fPIC  -g -O2 -Wall -c setErrorHandler.cpp -o setErrorHandler.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o RcppGSL.so RcppExports.o fastLm.o init.o setErrorHandler.o -L/usr/local/Cellar/gsl/2.5/lib -lgsl -lgslcblas -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
installing to /Users/kevin/Library/R/3.5/library/RcppGSL/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (RcppGSL)

The downloaded source packages are in
	‘/private/var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T/Rtmphya9bV/downloaded_packages’
```

The output of

```
R CMD config --all
```

would probably be helpful in diagnosing the issue.

**Comment by eddelbuettel** [comment] 2019-03-26 00:21
Agreed. If `./configure` works on the shell then the R setup is likely suspect.

**Comment by kevinushey** [comment] 2019-03-26 00:29
Also worth saying that if I try to re-build the tarball from unpacked sources (I do not understand why you're doing this?) I see:

```
kevin@zordon:~/Downloads
$ R --verbose CMD build --no-build-vignettes RcppGSL
* checking for file ‘RcppGSL/DESCRIPTION’ ... OK
* preparing ‘RcppGSL’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* saving partial Rd database
* checking vignette meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘RcppGSL_0.3.6.tar.gz’
```

and note that I get more output than you do (or you didn't share everything that was produced)

**Comment by nieder** [comment] 2019-03-26 09:45
@kevinushey: the output in the original comment is all that I get when building 0.3.6 from the unpacked CRAN tarball. I'm using Fink's (macOS package manager) R and build system.

I did some bisecting, and the part of commit 67b69614 that applies to man/RcppGSL-package.Rd causes the build failure. If I patch 0.3.4 to change man/RcppGSL-package.Rd (and 'fix' its MD5 checksum), then my build fails. If I revert the commit to man/RcppGSL-package.Rd in 0.3.5 and 0.3.6, then the build succeeds.

**Comment by eddelbuettel** [comment] 2019-03-26 11:17
For the record I asked on your behalf on rcpp-devel and Robin Hankin also has no issue:
http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2019-March/010306.html

Also note that using Fink's R may be the issue.  As far as I know you are supposed to use R from CRAN and its toolchain.
